;; e4c: structs autogenerated
label e4c.structs
;; e4c: structs impl autogenerated
label e4c.impl_structs
call main
;; e4c: autogenerated
label main
	align 10
	mov cycl,off
	call loop
	cli
	hlt
	;; e4c: autogenerated
	label loop
		dbg cycl
		loop loop
		ret
	ret
