;; e4c: structs autogenerated
label e4c.structs
;; e4c: structs impl autogenerated
label e4c.impl_structs
db my_variable,1 ;; e4c: create variable
db my_variable2,1 ;; e4c: create variable
ivar my_variable,0 ;; e4c: select variable
align 0 ;; e4c: offset 0
pub 23
;; e4c: save vars
push ds ;; e4c: save ds
push off ;; e4c: save offset
;; e4c: get variable
ivar my_variable,0 ;; e4c: variable
align 0 ;; e4c: offset 0
gub a ;; e4c: get variable value
pop off ;; e4c: load off
pop ds ;; e4c: load ds
ivar my_variable2,0 ;; e4c: select variable
align 0 ;; e4c: offset 0
mov [byte]a
